"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[ ❯](bright-cyan)'
error_symbol = '[ ❯](bright-red)'

[directory]
truncation_length = 0
truncate_to_repo = false
style = "bright-green"

[git_branch]
symbol = ""
format = "[$symbol$branch]($style) "
